# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-03 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('message_id', models.CharField(default=uuid.UUID('37101c0e-c201-46ff-bd80-2f852046ab2b'), max_length=1024)),
            ],
        ),
    ]
