# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-03 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('share_txt_sms_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default=uuid.UUID('706edcba-d6d2-4a55-9306-a1a328b3928d'), max_length=1024),
        ),
    ]
