# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-05 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_txt_sms_web_app', '0002_auto_20181003_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
